### ISSUE TITLE
Yarn install problem

### ISSUE THREAD

**Issue by b4b857f6ee** [luipir/GaliciaSustentable_deployment#1]
Hello :)

Os : CentOS 7, i can't found how to debug this.

I don't know yarn, any idea?

https://user-images.githubusercontent.com/36012515/98021016-0c4ce300-1e04-11eb-906f-912cd8505d2f.png

**Comment by luipir** [comment]
> Hello :)
> 
> Os : CentOS 7, i can't found how to debug this.
> 
> I don't know yarn, any idea?
> 
> https://user-images.githubusercontent.com/36012515/98021016-0c4ce300-1e04-11eb-906f-912cd8505d2f.png

seems more a grafana problem of the dev envitronment or indirectly yarn in centos.
Di d you readbasic documentation how to dev a grafana plugin? https://grafana.com/tutorials/build-a-panel-plugin/#3

**Comment by b4b857f6ee** [comment]
I was not using the nodejs v12 :)

It's install Thank you!

![image](https://user-images.githubusercontent.com/36012515/98101895-2550a500-1e93-11eb-815e-be7170cb0862.png)

**Comment by b4b857f6ee** [comment]
Sorry, the yarn dev or build didn't work

      1:1   error  Definition for rule '@typescript-eslint/class-name-casing' was not found                                                                                                                                                                                       @typescript-eslint/class-name-casing
      1:1   error  Definition for rule '@typescript-eslint/interface-name-prefix' was not found                                                                                                                                                                                   @typescript-eslint/interface-name-prefix
     18:10  error  Don't use `String` as a type. Use "string" instead                                                                                                                                                                                                             @typescript-eslint/ban-types
     36:55  error  Expected '===' and instead saw '=='                                                                                                                                                                                                                            eqeqeq
     68:19  error  Expected '===' and instead saw '=='                                                                                                                                                                                                                            eqeqeq
     80:20  error  Expected '===' and instead saw '=='                                                                                                                                                                                                                            eqeqeq
    108:39  error  Don't use `object` as a type. The `object` type is currently hard to use ([see this issue](https://github.com/microsoft/TypeScript/issues/21732)).
  Consider using `Record<string, unknown>` instead, as it allows you to more easily inspect and use the keys  @typescript-eslint/ban-types
    109:23  error  Expected '===' and instead saw '=='                                                                                                                                                                                                                            eqeqeq

  /home/user/GaliciaSustentable_deployment/dashboards/luipir-sunburst-panel/src/module.tsx
    1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found      @typescript-eslint/class-name-casing
    1:1  error  Definition for rule '@typescript-eslint/interface-name-prefix' was not found  @typescript-eslint/interface-name-prefix

  /home/user/GaliciaSustentable_deployment/dashboards/luipir-sunburst-panel/src/types.ts
    1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found      @typescript-eslint/class-name-casing
    1:1  error  Definition for rule '@typescript-eslint/interface-name-prefix' was not found  @typescript-eslint/interface-name-prefix

  ✖ 12 problems (12 errors, 0 warnings)



  Trace: Error: 12 linting errors found in 3 files
      at /home/user/GaliciaSustentable_deployment/dashboards/luipir-sunburst-panel/node_modules/@grafana/toolkit/src/cli/tasks/plugin.build.js:117:31
      at step (/home/user/GaliciaSustentable_deployment/dashboards/luipir-sunburst-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:136:27)
      at Object.next (/home/user/GaliciaSustentable_deployment/dashboards/luipir-sunburst-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:117:57)
      at fulfilled (/home/auser/GaliciaSustentable_deployment/dashboards/luipir-sunburst-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:107:62)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at /home/user/GaliciaSustentable_deployment/dashboards/luipir-sunburst-panel/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:24:29
      at step (/home/user/GaliciaSustentable_deployment/dashboards/luipir-sunburst-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:136:27)
      at Object.throw (/home/user/GaliciaSustentable_deployment/dashboards/luipir-sunburst-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:117:57)
      at rejected (/home/user/GaliciaSustentable_deployment/dashboards/luipir-sunburst-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:108:69)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
✖ 12 linting errors found in 3 files
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about thi

**Comment by luipir** [comment]
did you try yarn watch after yarn install?... I do not remember if I used yarn dev. I'm for use used yarn watch (that is base on yarn dev or at least reading package.json)

**Comment by luipir** [comment]
btw, at least eslint errors could be an eslint versioning problem

**Comment by b4b857f6ee** [comment]
Install Ok

[root@grafana luipir-sunburst-panel]# yarn install
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 1.54s.
[root@grafana luipir-sunburst-panel]#

yarn watch

![image](https://user-images.githubusercontent.com/36012515/98117015-72d80c80-1ea9-11eb-8f3e-4f174ca802be.png)
![image](https://user-images.githubusercontent.com/36012515/98117280-cc403b80-1ea9-11eb-96fb-0cde3eeaedbc.png)

**Comment by luipir** [comment]
sometimes yarn does not avoid code execution... as I said the code is not clean at all and if you want to remove that typescript type check free to modify the code. BTW you have to modify the code to get data json somewhere.
I would do in this way:
1) add the panel somewhere in a grafana dashboard
2) visualize or enter in edit mode of the panel
3) follow the error in the brawser debug  to find where the variable are NOT set => where you have to modify to adapt to your code.... that's the way I integrated it, with try and errors.
Let me know if you need a customized integration to your needs.

**Comment by b4b857f6ee** [comment]
Ok so i have it like this, i now i have to found how i can make a circle

![image](https://user-images.githubusercontent.com/36012515/98133962-82ae1b80-1ebe-11eb-834c-2328fb98130d.png)

What i want to do :  
![image](https://user-images.githubusercontent.com/36012515/98134027-9b1e3600-1ebe-11eb-9220-b4eaf57e14a6.png)

**Comment by luipir** [comment]
here a base json that is the base to populate with more data and sored in a db... from this db is get and shown in the panel
https://github.com/luipir/qgis-galiciasustentable-plugin/blob/master/galiciasustentable/test_data/sunburst_conf.json
a hability more of this panel is that it is used to browse other panels, e.g. it is used as interface to navigate and setup data of other panels, but probably is something that you do not need.

**Comment by b4b857f6ee** [comment]
Ok i understand the structure of the json. but you mean my data need to be as this json to work? My data are in Elasticsearch.
I don't get it, how to use your json to populate data to make it work with the sunburst.

I have no options, it normal?
![image](https://user-images.githubusercontent.com/36012515/98139549-9e1c2500-1ec4-11eb-8bd9-2170acfdd3af.png)

And how i can browse other panel to use the data from these others panel.
Sorry for all of this questions :/....

**Comment by luipir** [comment]
well this is a highly customised panel veltically oriented for the project I developed. It's not intended to be general purpose! BTW as I did reverse engineering other code to create this one, give a look of the code, it's really not difficult to read. 
Probably you need to get data from the data frame (a query to elasticsearch), create some routine to prepare a json and then apply visualization.
e.g. I read an already prepared json from a query here https://github.com/luipir/GaliciaSustentable_deployment/blob/master/dashboards/luipir-sunburst-panel/src/SunburstPanel.tsx#L37
If you need more support, sorry I would ask you to upgrade to a professional consultancy.... in other way, the code is there and freely available.

**Comment by b4b857f6ee** [comment]
Oh ok sorry then ;). I understand!
